name: gfxraaz
description: GFX Tool with Shizuku
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  permission_handler: ^11.4.0
  shizuku_api: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true